<a href="https://colab.research.google.com/github/Rushikeshbgaikwad/python/blob/main/Copy_of_allnumpyarr.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
'''Numpy is a general purpose array-processing package.It provides a high performance multidimenssional array object and tools for working with
these array.It is the fundamental package for scientific computing with python'''
'''Array is a data structure that stores values of same data type.In python the main difference between arrays and lists,python lists can contain values to
corresponding to different data types,arrays in python can only contain values corresponding to same data type.'''
import numpy as np
my_list=[1,2,3,4,5]
arr=np.array(my_list)
type(arr)
print(arr)

[1 2 3 4 5]


In [ ]:
arr.shape

(5,)

In [ ]:
#multidimenssional array
my_list1=[1,3,4,5,2]
my_list2=[3,4,5,6,7]
my_list3=[6,7,8,9,1]
arr=np.array([my_list1,my_list2,my_list3])
arr

array([[1, 3, 4, 5, 2],
       [3, 4, 5, 6, 7],
       [6, 7, 8, 9, 1]])

In [ ]:
arr.shape

(3, 5)

In [ ]:
arr.reshape(5,3)

array([[1, 3, 4],
       [5, 2, 3],
       [4, 5, 6],
       [7, 6, 7],
       [8, 9, 1]])

In [ ]:
arr.shape

(3, 5)

In [ ]:
#indexing
#Accessing the array elements
arr

array([[1, 3, 4, 5, 2],
       [3, 4, 5, 6, 7],
       [6, 7, 8, 9, 1]])

In [ ]:
#arr=np.array([1,2,3,4,5,6,7,8,9])
#arr[3]

4

In [ ]:
#arr
arr


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr=np.array([[1,2,3,4,5],
             [2,3,4,5,6],
             [9,7,6,8,9]])
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [ ]:
arr[:,:]

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [ ]:
arr[0:2,:]

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6]])

In [ ]:
arr[:2,0:2]

array([[1, 2],
       [2, 3]])

In [ ]:
arr[:1,]

array([[1, 2, 3, 4, 5]])

In [ ]:
arr[1:,3:]

array([[5, 6],
       [8, 9]])

In [ ]:
arr=np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.linspace(1,10,50)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [ ]:
#copy function and broadcasting
arr[2:]=500
arr

array([  1,   2, 500, 500, 500])

In [ ]:
arr1=arr

In [ ]:
arr1[2:]=500
print(arr1)

[  1   2 500 500 500]


In [ ]:
arr

array([  1,   2, 500, 500, 500])

In [ ]:
#array is a reference type
#integers are a value type
arr1=arr.copy()
print(arr)
arr1[3:]=1000
print(arr1)

[  1   2 500 500 500]
[   1    2  500 1000 1000]


In [ ]:
arr

array([  1,   2, 500, 500, 500])

In [ ]:
#some conditions very useful in Exploratory Data Analysis
val=2
arr<2

array([ True, False, False, False, False])

In [ ]:
val=2
arr*2

array([   2,    4, 1000, 1000, 1000])

In [ ]:
##create arrays and reshape
np.arange(0,10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [ ]:
np.ones(4)

array([1., 1., 1., 1.])

In [ ]:
np.ones((2,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [ ]:
#random distributions
np.random.rand(3,3)

array([[0.51873499, 0.30069658, 0.1907528 ],
       [0.97475634, 0.69316732, 0.31078485],
       [0.27445291, 0.24467449, 0.23437915]])

In [ ]:
arr_ex=np.random.randn(4,4)#standard normal distribution
arr_ex

array([[ 0.89372264,  0.1600498 , -0.40029819, -0.08850917],
       [ 1.02152868,  0.0870016 ,  0.3420088 ,  0.34222818],
       [ 0.21567956,  1.13109309,  0.16373666, -0.13689816],
       [-0.87173384, -0.4978628 , -2.4513166 ,  0.72913594]])

In [ ]:
np.random.randint(0,500,8).reshape(4,2)

array([[  0, 191],
       [107, 445],
       [285, 431],
       [ 48, 209]])

In [ ]:
np.random.random_sample((1,5))

array([[0.1413249 , 0.27514076, 0.0907728 , 0.04201235, 0.40955863]])