<a href="https://colab.research.google.com/github/Rushikeshbgaikwad/python/blob/main/npindexing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Write a NumPy program to find the index of the sliced elements as follows from a given 4x4 array.
import numpy as np    
x = np.reshape(np.arange(16),(4,4))
print("Original arrays:")
print(x)
print("Sliced elements:")
result = x[[0,1,2],[0,1,3]]
print(result)

Original arrays:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
Sliced elements:
[ 0  5 11]
